image:
  repository: redis
  tag: 7-alpine
  pullPolicy: IfNotPresent

service:
  port: 6379

persistence:
  enabled: false    # set true for production

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"