{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-worker-scaledobject
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-worker

  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}

  triggers:
    - type: redis
      metadata:
        address: {{ .Values.keda.redisAddress | quote }}
        listName: {{ .Values.keda.queue | quote }}
        listLength: {{ .Values.keda.queueLength | quote }}
        databaseIndex: {{ .Values.keda.redisDatabase | quote }}
        enableTLS: "false"
{{- end }}