{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flower-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-flower
  ports:
    - protocol: TCP
      port: 5555           # ← change from 80 to 5555
      targetPort: 5555
  type: ClusterIP
{{- end }}