replicaCount: 1

image:
  repository: zubairhassan652/fastapi
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  ingressClassName: nginx
  host: fastapi.example.com
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUPercent: 90
  targetMemoryPercent: 90

secret:
  name: redis-secret