# keda-argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.14.2

    helm:
      values: |
        crds:
          install: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true                # ← force replace CRDs if already exist