apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-fastapi
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}   # ← only set if HPA disabled
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: REDIS_URL
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3