apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
  labels:
    app: {{ .Release.Name }}-fastapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secret     # ← secret name
                  key: REDIS_URL         # ← key inside secret
            
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}